#!/bin/bash
set -euo pipefail

if [ -f "$(dirname "$0")/venv/Scripts/activate" ]; then
  # shellcheck disable=SC1091
  source "$(dirname "$0")/venv/Scripts/activate"
fi

python -m docwatcher.cli "$@"
